const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Plugins.video,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Timer,
		C3.Behaviors.LOS,
		C3.Behaviors.Follow,
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{VIDA: 0},
	{cenario: 0},
	{estado: 0},
	{Attack: 0},
	{folha: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Alex: 0},
	{Sólido: 0},
	{piso: 0},
	{Teclado: 0},
	{sensor_patru_direita: 0},
	{sensor_patru_esquerda: 0},
	{Bullet: 0},
	{tiro_farao: 0},
	{Sprite: 0},
	{tiro_alex: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Direcao: 0},
	{mumia: 0},
	{espinhos: 0},
	{folha_hud: 0},
	{vida_hud: 0},
	{Texto: 0},
	{Tilemap: 0},
	{TiledBackground: 0},
	{Plataforma2: 0},
	{plataforma3: 0},
	{fundo: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{porta: 0},
	{Vídeo: 0},
	{Sprite7: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Mouse: 0},
	{Toque: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{ATTACK: 0},
	{HEALTH: 0},
	{Solid: 0},
	{Timer: 0},
	{Flash: 0},
	{LineOfSight: 0},
	{Follow: 0},
	{farao: 0},
	{spaw_mumia: 0},
	{BarradevidaBoss: 0},
	{VidaBoss: 0},
	{VidaBoss2: 0},
	{Vídeo2: 0},
	{FOLHAS: 0}
];

self.InstanceType = {
	cenario: class extends self.ISpriteInstance {},
	Alex: class extends self.ISpriteInstance {},
	piso: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	sensor_patru_direita: class extends self.ISpriteInstance {},
	sensor_patru_esquerda: class extends self.ISpriteInstance {},
	tiro_farao: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	tiro_alex: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	mumia: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	folha_hud: class extends self.ISpriteInstance {},
	vida_hud: class extends self.ISpriteInstance {},
	folha: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Plataforma: class extends self.ITilemapInstance {},
	Plataforma2: class extends self.ISpriteInstance {},
	plataforma3: class extends self.ISpriteInstance {},
	fundo: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	farao: class extends self.ISpriteInstance {},
	spaw_mumia: class extends self.ISpriteInstance {},
	BarradevidaBoss: class extends self.IInstance {},
	VidaBoss: class extends self.ISpriteInstance {},
	VidaBoss2: class extends self.ISpriteInstance {},
	Vídeo2: class extends self.IWorldInstance {}
}